mongodb: # mongodb配置
  is_auth: true
  user: "adminUser" # 用户
  pass: "adminPass" # 密码
  dbname: "admin" # 数据库
  collection: "event_log" # 集合名
  hosts:
    - "139.199.167.112:27017" # 主机名:端口号(例如"localhost:27017")
rabbit_mq: # rabbit mq 配置
  host: "139.199.167.112" # 主机
  port: "5672" # 端口
  vhost: "/" # 虚拟主机
  user: "admin" # 用户名
  pass: "admin" # 密码
  exchange_name: "exchange_live" # 交换器名称
rabbit_mq_ping_interval_time: 20 # 心跳间隔时间: 20秒